openapi: 3.0.1

info:
  title: carts API
  description: API to manage carts
  version: 1.0.0

servers:
  - url: http://localhost:8080

paths:

  /api/carts/{cid}:
    get:
      summary: Get cartcart
      description: Retrieve a list of carts
      parameters:
        - name: cid
          in: path
          description: The cart mongo id.
          required: true
          schema:
            type: string

      responses:
        "200":
          description: The specific cart.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: OK
                  payload:
                    type: object
                    properties:
                      _id:
                        type: string
                      products:
                        type: array
                        items:
                          $ref: "#/components/schemas/Product"
                      quantity:
                        type: integer
                      date:
                        type: string
        "400":
          description: Error details
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: El carrito no existe.
    put:
      summary: Update a cart with n products, only for specific users (user, premium)
      description: Update the especific cart with the products sent.
      parameters:
        - name: cid
          in: path
          description: The cart mongo id.
          required: true
          schema:
            type: string
      security:
        - basicAuth: []

      responses:
        "200":
          description: The confirmation of the operation.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: El carrito {cid} fue actualizado de forma exitosa.
        "400":
          description: Error details
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "{errorName}: No se pudo completar la operación."
        "401":
          description: Error details
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ERROR
                  error:
                    type: string
                    example: Permisos insuficientes.

    delete:
      summary: Delete the cart products, only for specific users (user, premium)
      description: Delete a all the products of a especific cart.
      parameters:
        - name: cid
          in: path
          description: The cart mongo id.
          required: true
          schema:
            type: string
      security:
        - basicAuth: []

      responses:
        "200":
          description: The confirmation of the operation.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: Se eliminaron los productos del carrito {cid} de forma exitosa.
        "400":
          description: Error details
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ERROR
                  error:
                    type: string
                    example: "CastError: No se pudo realizar la operación."
        "401":
          description: Error details
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ERROR
                  error:
                    type: string
                    example: Permisos insuficientes.

  /api/carts/product/{pid}:
    post:
      summary: Add or update an item in the cart only for specific users (user, premium).
      description: Add a new product to the cart or update it if it already exists.
      parameters:
        - name: cid
          in: path
          description: The cart mongo id.
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quantity:
                  type: integer
              required:
                - quantity
      security:
        - basicAuth: []

      responses:
        "200":
          description: A list of users
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: El carrito {id} fue actualizado de forma exitosa.
        "400":
          description: Error details
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: El carrito no existe.
        "401":
          description: Error details
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ERROR
                  error:
                    type: string
                    example: Permisos insuficientes.

  /api/carts/purchase:
    post:
      summary: Finish a purchase, only for specific users (user, premium).
      description: Complete de purchase.
      security:
        - basicAuth: []

      responses:
        "200":
          description: A list of users
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: OK
                  payload:
                    type: string
                    example: Su compra {id} se ha finalizado.
                  alerts:
                    type: array
                    items:
                      $ref: "#/components/schemas/Alert"
                  
        "400":
          description: Error details
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: No se pudo concretar la operación.
        "401":
          description: Error details
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ERROR
                  error:
                    type: string
                    example: Permisos insuficientes.

  /{cid}/product/{pid}:
    put:
      summary: Update a cart with a specific product that already exists in the cart, only for specific users (user, premium)
      description: Update the especific cart with the products sent.
      parameters:
        - name: cid
          in: path
          description: The cart mongo id.
          required: true
          schema:
            type: string
        - name: pid
          in: path
          description: The product mongo id.
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quantity:
                  type: integer
              required:
                - quantity
      security:
        - basicAuth: []

      responses:
        "200":
          description: The confirmation of the operation.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: El carrito {cid} fue actualizado de forma exitosa.
        "400":
          description: Error details
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ERROR
                  error:
                    type: string
                    example: "El producto no se encuentra en el carrito."
        "401":
          description: Error details
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ERROR
                  error:
                    type: string
                    example: Permisos insuficientes.

    delete:
      summary: Delete a cart, only for specific users (user, premium)
      description: Delete the especific product in the cart.
      parameters:
        - name: cid
          in: path
          description: The cart mongo id.
          required: true
          schema:
            type: string
        - name: pid
          in: path
          description: The product mongo id.
          required: true
          schema:
            type: string
      security:
        - basicAuth: []

      responses:
        "200":
          description: The confirmation of the operation.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: El carrito {cid} fue actualizado de forma exitosa.
        "400":
          description: Error details
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ERROR
                  error:
                    type: string
                    example: "El producto no se encuentra en el carrito."
        "401":
          description: Error details
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ERROR
                  error:
                    type: string
                    example: Permisos insuficientes.


components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: string
        title:
          type: string
        description:
          type: string
        thumbnails:
          type: string
        price:
          type: number
        category:
          type: string
        stock:
          type: string
        code:
          type: string
        status:
          type: boolean
        owner:
          type: string
    Alert:
      type: object
      properties:
        id:
          type: string
        message:
          type: string
        
